const LOGIN = "LOGIN"
const LOGOUT ="LOGOUT"
const PROJECTLIST = "PROJECTLIST"
const PROJ_REQ ="PROJ_REQ"
const CURR_TASK = "CURR_TASK"
const ALL_TASKS = "ALL_TASKS"
const PROJ_FILLTER = "PROJ_FILLTER"

export {LOGIN ,LOGOUT,PROJECTLIST,PROJ_REQ,CURR_TASK,ALL_TASKS,PROJ_FILLTER}